tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

cask "adobe-acrobat-reader"
cask "discord"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "postman"
cask "spotify"
cask "vlc"
cask "visual-studio-code"
cask "whatsapp"
cask "node"
cask "yarn"
